parameters: 
  insprie: 
    serialNum: /dev/GripperDriver1
    baudrate: 115200
    speed: 500
    force: 200
    size_max: 980
    size_min: 0
    
  airpowere:
    robotIp: 192.168.98.2
    robotPort: 23234
    portIndex: 0
    openVlaue: false
    closeValue: true
